export { checkGeekbangDomain } from './src/checkGeekbangDomain'
export { copyHandler } from './src/copyHandler'
export { cutStr } from './src/cutStr'
export { date } from './src/date'
export { getTrueLength } from './src/getTrueLength'
export { isBottom } from './src/isBottom'
export { isInWeixin, isInWXMiniProgram } from './src/isInWeixin'
export { isMac } from './src/isMac'
export { isMobile } from './src/isMobile'
export { isRealHeightMoreThanVisibleHeight } from './src/isRealHeightMoreThanVisibleHeight'
export { offset } from './src/offset'
export { subString } from './src/subString'
